---
name: 'Run Tests'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

permissions:
  checks: 'write'
  pull-requests: 'write'

env:
  TEST_RESULTS_PATH: '.bats/test-results'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Show GNU make version'
        run: 'make --version'

      - name: 'Run tests'
        run: |
          BATS_EXTRA_FLAGS="--report-formatter junit -o ${TEST_RESULTS_PATH}"
          mkdir -p "${TEST_RESULTS_PATH}"
          make BATS_EXTRA_FLAGS="${BATS_EXTRA_FLAGS}" test

      - name: 'Publish test results'
        uses: 'EnricoMi/publish-unit-test-result-action@v1'
        if: 'always()'
        with:
          files: |
            .bats/test-results/*.xml
            .bats/test-results/**/*.xml
